// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcNm75Z8wY7xjIskSUHWvZVi-P7NrYh9s',
    appId: '1:975222531949:android:c29ddf3edeccf757addc64',
    messagingSenderId: '975222531949',
    projectId: 'ayush82-ee6b9',
    storageBucket: 'ayush82-ee6b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhNxQ6J5K1G2H3I4J5K6L7M8N9O0P1Q2R3',
    appId: '1:975222531949:ios:c29ddf3edeccf757addc64',
    messagingSenderId: '975222531949',
    projectId: 'ayush82-ee6b9',
    storageBucket: 'ayush82-ee6b9.firebasestorage.app',
    iosClientId: 'YOUR_IOS_CLIENT_ID.apps.googleusercontent.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcNm75Z8wY7xjIskSUHWvZVi-P7NrYh9s',
    appId: '1:975222531949:web:YOUR_WEB_APP_ID',
    messagingSenderId: '975222531949',
    projectId: 'ayush82-ee6b9',
    authDomain: 'ayush82-ee6b9.firebaseapp.com',
    storageBucket: 'ayush82-ee6b9.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );
}
